### ISSUE TITLE
Sponsoring and donating

### ISSUE THREAD

**Issue by LeoColman** [blockbasti/just_another_workout_timer#102]
Hi!
I've being using this app on a daily basis for quite a while, and I'd like to send the author a cup of coffee.

Is that possible?
If it isn't, could you add some sponsoring information? I suggest ko-fi or buymeacoffee

**Comment by utkb** [comment]
I want it too.

**Comment by blockbasti** [comment]
@LeoColman @utkb Thank you for using and liking my app. I have created a ko-fi (https://ko-fi.com/blockbasti) where you can donate, if you like.
