### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by utkb** [blockbasti/just_another_workout_timer#103]
Hello,

I translated strings to Turkish language and added translated file as txt. Could you add to application?

P.S. Thank you for this nice application. It is simple and effective. As a physiotherapist I will recommend it to my patients.
[intl_tr.txt](https://github.com/blockbasti/just_another_workout_timer/files/7913837/intl_tr.txt)

Best regards,
Utku Berberoğlu

**Comment by blockbasti** [comment]
Thank you for translating the app to turkish and recommending it to more people. I will add this soon and release an update.
