### ISSUE TITLE
Pressing skip twice before starting a workout will break the app

### ISSUE THREAD

**Issue by ShemJM** [blockbasti/just_another_workout_timer#120]
**Describe the bug**
The timer will still tick but the app is broken for the first workout. If you let the timer countdown until the next set then it will be okay again. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Select a workout to start on the home screen.
2. Before pressing play, press skip twice.
3. The progress bar will decrease.
4. Press play.
5. The timer will tick down to the first workout and then be displayed weirdly. 

**Expected behaviour**
I would expect the app just to skip to the next workout each time you press the skip button. 

**Smartphone (please complete the following information):**
 - Honor 10 lite and Moto G60
 - Android 11 and 12

**Comment by ShemJM** [comment]
@blockbasti I am happy to try to fix this one but I have not worked with mobile apps before so not sure how to get setup. Is there a discord server or something for development of this app?

**Comment by blockbasti** [comment]
There is currently no Dev Discord. I'm currently working on refactoring some large parts of the code base, including the workout page.

If you want to start contributing to the app, you just need Flutter and Android Studio installed. Then you can start developing. There are some small things you need to do once, which are described in the [README](https://github.com/blockbasti/just_another_workout_timer#contributing).
