### ISSUE TITLE
Worklist Graphical Improvements

### ISSUE THREAD

**Issue by Undermmon** [blockbasti/just_another_workout_timer#13]
Some graphical improvements that would greatly improve the app usability:

-The timer should be fixed at the top of screen at all times. Its annoying when i want to scroll the list and it disappears.
-The current exercise set title also should be below the timer at all time, so its easy to see in which set your currently are in, even if you are at the middle/end of the set.
-The current active exercise should be always centralized or at the top below the current set.

**Comment by blockbasti** [comment]
> -The timer should be fixed at the top of screen at all times. Its annoying when i want to scroll the list and it disappears.

this is already fixed on my local branch, should be committed soon

> -The current exercise set title also should be below the timer at all time, so its easy to see in which set your currently are in, even if you are at the middle/end of the set.

so you mean, a text like 'Set 1' in the top card with the timer?

> -The current active exercise should be always centralized or at the top below the current set.

if the current set is long enough to require scrolling, the marked active exercise should stay on screen?

**Comment by Undermmon** [comment]
> if the current set is long enough to require scrolling, the marked active exercise should stay on screen?

Exactly. This way, you can visually see the next / previous exercises automatically, without the need to scroll the list, because doing it is difficult during the exercises. This way only relevant info is shown, in the current way once your active exercise leaves the screen you are presented with irrelevant info.
