### ISSUE TITLE
Skip exercises and sets during workout

### ISSUE THREAD

**Issue by blockbasti** [blockbasti/just_another_workout_timer#20]

**Comment by zcattacz** [comment]
This is not working on current 1.9.1 any more. On my Android 9 phone, Skip exercises  ( >|, |<) does nothing either when the workout  is  not started, started or paused.  Maybe worth a recheck ?

**Comment by zcattacz** [comment]
after some install/uninstall tweaking the TTS setting,  it magically start to function .  Thanks for the wonderful work.
