### ISSUE TITLE
f-droid not updating since 1.1.1

### ISSUE THREAD

**Issue by omichaelo** [blockbasti/just_another_workout_timer#27]
The latest f-droid version is 1.1.1, added on January 30. I am not a developer but, looking at info provided by [F-Droid Monitor](https://monitor.f-droid.org/builds/running), the app seems to have failed to build. 

It would be nice if someone can look into this, as switching to the github version means losing all data.

**Comment by blockbasti** [comment]
F-Droid has just successfully built v1.4.0 (see https://f-droid.org/wiki/page/com.blockbasti.justanotherworkouttimer/lastbuild_20210221), so it should be released soon. Hotfixes v1.4.1 and v1.4.2 should be released soon as well.

The update process on F-Droid can be a bit slow, but there is nothing i can do about that.

**Comment by omichaelo** [comment]
I see. Sorry if it wasn't a real issue. I'm glad it successfully builds now.
