### ISSUE TITLE
Ordering of workout list??

### ISSUE THREAD

**Issue by polyonymous** [blockbasti/just_another_workout_timer#30]
Not sure if this is a question, bug or request...

The order of my created workouts seems random, or at least I can't guess how it's ordering itself. I do know that it is not based on: 
- alphabetisation
- workout creation/modification date
- workout length
- recently played workouts

Knowing what variable the ordering is based on, or having it changed to one of the above (alphabetical is my preference) would be very useful. Also/alternatively, being able to drag & reorder the workouts would help. 

My use case involves a lot of separate workouts, and I would like to add even more but have hit a limit as to a manageable/navigable number when they are randomly listed. (Also being able to group workouts would be cool, but I'll open a separate feature request for that.)

I'm really enjoying this app (after trying several others) and appreciate how actively it's being developed. Cheers.

**Comment by blockbasti** [comment]
Thank you for the feedback.

Currently there is no fixed order of the workouts. It is a good idea to give the user some options on how to sort them.
