### ISSUE TITLE
Cannot create Workouts (F-Droid 1.4.0)

### ISSUE THREAD

**Issue by f0rdprefect** [blockbasti/just_another_workout_timer#31]
## DO

F-Droid Version 1.4.0 

Try to add items to workout

## GET

Nothing

## EXPECT

Fill the list with workout items

## REMARK

I am running Android 10 (OxygenOS) on a OnePlus 6T

Now I just tried the github version and it works. Let me know if you need further testing. Nice App!

**Comment by blockbasti** [comment]
This was already reported in #25 was fixed in version 1.4.1. We just have to wait until F-Droid builds and releases the update.
