### ISSUE TITLE
Adding exercise or rest does not work

### ISSUE THREAD

**Issue by kamilkurzawa** [blockbasti/just_another_workout_timer#32]
Since one of the recent updates, adding new exercise or rest does not work. When you click on one of the icons, the screen turns gray. 

![Screenshot_20210303-124413](https://user-images.githubusercontent.com/51320145/109801496-d63b3680-7c1e-11eb-8676-fd83e1b650e1.jpg)

![Screenshot_20210303-124439](https://user-images.githubusercontent.com/51320145/109801494-d5a2a000-7c1e-11eb-86db-091f48adca1c.jpg)

I was able to create a workout in one of the previous versions.

**Comment by mschmidm** [comment]
This issue is already fixed with v1.4.1 which is available on GitHub, unfortunately F-Droid is a bit slow with releasing updates.
Please be aware that all workouts are deleted when switching from F-Droid to the GitHub version. You would have to backup the local workout folder first.

**Comment by kamilkurzawa** [comment]
Well, that's something I wish I knew earlier 🙂 I tried to download the latest from github and install it over the f-droid one but it looks like it did not update and fortunately the workouts were not removed. 

In any case, thank you for the reply. I'll wait for it to be available on f-droid.

Keep up the good work! I love the app and constant improvements!
