### ISSUE TITLE
Feature Request: Time settings

### ISSUE THREAD

**Issue by Starto96** [blockbasti/just_another_workout_timer#38]
Hi,
Thank you for your cool APP, I'm really enjoying it :). I have a request, if possible.

**Is your feature request related to a problem? Please describe.**
I'm doing really specific workouts for climbing an there the timing is very important. This means that i have like 7 seconds workout and 3 seconds rest. At the moment it is not possible to achieve this with your app because you can set the intervals just with a 5 seconds step. Would it be possible to change this?

**Describe the solution you'd like**
There are two way:
- You could tap on the time that you are setting and this would toggle the step from 5 to 1 second and vice versa.
- Or Just give the possibility to set the time by hand

Thank you very much for your work!

**Comment by blockbasti** [comment]
Thanks for the feature request fellow climber 😃 Yeah, doing 7-3 repeaters currently isn't possible. I'm looking for a way to make finer adjustments to the duration of each exercise without impacting UX too much.

**Comment by Starto96** [comment]
Wow this was really fast. Thank you so much :)
