### ISSUE TITLE
Simple sounds don't play

### ISSUE THREAD

**Issue by tmtvl** [blockbasti/just_another_workout_timer#44]
**Describe the bug**
The app doesn't play sound when using sound effects.

**To Reproduce**
1. Go to settings.
2. Select "Use sound effects" under Sound output.
3. Start a workout set.

**Expected behavior**
The app should play the standard beep sound effect from assets.

**Smartphone (please complete the following information):**
 - Device: Sony Xperia XA2
 - OS: Android version 9.
 - Version: F-Droid 1.6.0

**Additional context**
The TTS works fine.

**Comment by blockbasti** [comment]
Hey, thanks for reporting an issue. Sadly i can't reproduce the bug on my device.

Sound effects play using the notifications channel. Do you have your notification volume low/off? Did it work on older versions of the app?

**Comment by tmtvl** [comment]
Ah, that's interesting. Yes, when I turn on the notification volume the sound effects work. I was expecting it to use the media channel like the TTS does, that was silly of me.
