### ISSUE TITLE
Workout saving

### ISSUE THREAD

**Issue by krash84** [blockbasti/just_another_workout_timer#47]
Version 1.6.0

**Describe the bug**
Saving the workout is not reliable. If you press "Save" button nothing happens (return to workout list is expected), if you press "save" twice the app asks if you want to rewrite existing workout (it's not obvious for the user that he had already saved it). Besides you can damage other workouts with this feature. Sometimes after saving you see empty list (all previously created workouts are erased). I think the program should let to have many workouts with the same name (it is much better than to have a risk of damaging already created ones).

**To Reproduce**
1. Go to workout list
2. Click on new workout
3. Fill the form to save
4. Click save
5. Nothing happens

**Expected behavior**
You should see workout list with saved workout (it is common behaviour in many other apps).

**Comment by alphanerdgen** [comment]
A toast notification saying the workout has been saved would also be nice.
