### ISSUE TITLE
Dedicated Import/Export Option

### ISSUE THREAD

**Issue by alphanerdgen** [blockbasti/just_another_workout_timer#49]
Folders within Android/data are no longer accessible in Android 11 thanks to Google's new policy. Therefore a dedicated option to import/export workouts is required.

**Comment by justsomehumanbeing** [comment]
I second this. 
I switched devices and was able to export (due to old android) manually but i can not import on the new device due to the security policy.

**Comment by jdaviescoates** [comment]
I can't wait for Version 2!.

I love this app, it does exactly what I want, and it does it very well. 

But I've just got a new phone so now need to be able to export/ import.

Is there a guestimate timeline for when v2 with this feature included will be available? 

Many thanks for your great work!

**Comment by blockbasti** [comment]
@jdaviescoates  Soon™ ;)

I'm currently ironing out a last few bugs. Release could be in the next few days.

**Comment by jdaviescoates** [comment]
Fantastic!

I guess that's why  the readme already says:

> You can export individual workouts or create an export of all your workouts and import them later. You can also transfer them to another device.

There is currently actually no way to do that, right?

**Comment by blockbasti** [comment]
There is a way, which might work, depending on your device/Android version. See https://github.com/blockbasti/just_another_workout_timer/blob/release/README.md#how-to-backup--restore-your-workouts

**Comment by jdaviescoates** [comment]
Ah, OK, thanks! I might not even get the chance to try that before the next release, but good to know it's there if I get desperate.
