### ISSUE TITLE
Name of the App

### ISSUE THREAD

**Issue by alphanerdgen** [blockbasti/just_another_workout_timer#53]
Will you consider changing the name of the app? It's so long that the app itself can't display it completely.

**Comment by blockbasti** [comment]
@alphanerdgen do you mean the text in the header of the home screen or the text in the launcher?

**Comment by alphanerdgen** [comment]
I meant within the app itself (in the blue strip on top). This happens on smaller Android phones.

 Even then maybe should consider changing the name. Current name seems flippant.

**Comment by StefRe** [comment]
I like the name, it follows a traditional software naming pattern. Following the convention, you maybe could just shorten it to JAWT in the app bar.
