### ISSUE TITLE
Android 11 - Lacks manifest settings for TTS

### ISSUE THREAD

**Issue by adamnew123456** [blockbasti/just_another_workout_timer#62]
# Problem

I've been using JAWT for a few months with Android 8 and been very satisfied with it. I flashed my phone to update to Android 11 (Lineage 18.1) and could not enable TTS after upgrading. I confirmed that I have the TTS engine and voices (Google TTS/US English pack) installed. I tried both 1.6 from F-Droid and 1.7 from the release page but both versions show that option as disabled.

The reason why comes down to a change to the [TextToSpeech](https://developer.android.com/reference/android/speech/tts/TextToSpeech) API made for Android 11, where apps using the service have to declare that they use a TTS intent. Without this Flutter TTS [will fail when initializing the TTS engine](https://github.com/dlutton/flutter_tts/blob/master/android/src/main/java/com/tundralabs/fluttertts/FlutterTtsPlugin.java#L202) - you can see this by filtering for a *Failed to initialize TextToSpeech* message in logcat.

# Changes

I have no idea whether this is suitable for inclusion into upstream - if not, it should at least help anyone who wants to make local builds for Android 11.

1. Make sure the build is configured to use API level 30.
2. [Update the Gradle build dependency](https://stackoverflow.com/a/62969918) so that the build tools are aware of the new manifest elements.
3. [Declare the TTS_SERVICE intent in the manifest](https://github.com/dlutton/flutter_tts/issues/230).
4. Rebuild as normal.

The resulting app-release.apk has a functional TTS option.

```diff
diff --git a/android/app/src/main/AndroidManifest.xml b/android/app/src/main/AndroidManifest.xml
index 34460c7..91581e8 100644
--- a/android/app/src/main/AndroidManifest.xml
+++ b/android/app/src/main/AndroidManifest.xml
@@ -1,5 +1,11 @@
 <manifest xmlns:android="http://schemas.android.com/apk/res/android"
     package="com.blockbasti.just_another_workout_timer">
+    <queries>
+        <intent>
+            <action android:name="android.intent.action.TTS_SERVICE" />
+        </intent>
+    </queries>
+
    <application
         android:label="Just Another Workout Timer"
         android:icon="@mipmap/launcher_icon"
diff --git a/android/build.gradle b/android/build.gradle
index bb4efc8..dc46985 100644
--- a/android/build.gradle
+++ b/android/build.gradle
@@ -6,7 +6,7 @@ buildscript {
     }
 
     dependencies {
-        classpath 'com.android.tools.build:gradle:3.5.0'
+        classpath 'com.android.tools.build:gradle:3.5.4'
         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
     }
 }
```

**Comment by blockbasti** [comment]
Hmm, strange. I'm using the app myself on Android 11 (and now 12) and had no problems with TTS.

As this seems to be required by the official documentation, could you create a pull request containing these changes? Thanks for making such a detailed bug report!
