### ISSUE TITLE
Something's Wrong with the Numbering System

### ISSUE THREAD

**Issue by alphanerdgen** [blockbasti/just_another_workout_timer#67]
**With A-Z ordering**:

![Jawt a-z](https://user-images.githubusercontent.com/83120103/120314138-8ab92700-c2f8-11eb-9d10-9458ab51a685.png)

**With the other one** (what's it called, BTW?):

![jawt 2](https://user-images.githubusercontent.com/83120103/120314227-a3c1d800-c2f8-11eb-81ea-3959f029e9f0.png)

**Version**: 1.7.0

**Comment by blockbasti** [comment]
@alphanerdgen can you please describe the bug in more detail?

**Comment by alphanerdgen** [comment]
@blockbasti Sorry it happened by mistake. I've edited it now.

**Comment by blockbasti** [comment]
Oh now i see. The second one orders by duration. The first one is sorting the numbers alphabetically, that's why the order is wrong. I'll see what i can do to fix this
